[package]
name = "kalancho"
version = "0.1.0"
edition = "2021"

[dependencies.reqwest]
version = "0.12.9"
default-features = false
features = ["default-tls"]

[dependencies.tokio]
version = "1.41.0"
default-features = false
features = ["macros", "rt-multi-thread"]
